<?php
/**
 * Copyright (c) 2023 KOUNT, INC.
 * See COPYING.txt for license details.
 */
/* @var $block \Kount\Kount2FA\Block\Provider\Google */
?>
<div class="login-container">
    <?php if ($block->is2faConfiguredForCustomer()): ?>
        <div class="block block-customer-login" style="width: 100%">
            <div class="block-content">
                <div class="block block-customer-login" style="width: 48%">
                    <p><?php echo __('Open your Google Authenticator app and enter the 6-digit code to log in.'); ?></p>
                    <div class="block-content">
                        <form class="form contact" style="float: left; width: 35%" action="<?php /* @escapeNotVerified */ echo $block->getAuthenticateFormAction(); ?>" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                            <input type="hidden" name="secret" value="<?php /* @escapeNotVerified */ echo $block->getSecretCode(); ?>" />
                            <fieldset class="fieldset" style="margin-bottom: 0">
                                <div class="field name required">
                                    <label class="label" for="code"><span><?php /* @escapeNotVerified */ echo __('Authentication Code') ?></span></label>
                                    <div class="control">
                                        <input name="code" id="code" title="<?php /* @escapeNotVerified */ echo __('Authentication Code') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                    </div>
                                </div>
                            </fieldset>
                            <div class="actions-toolbar">
                                <div class="primary">
                                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Authenticate') ?>" class="action submit primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Authenticate') ?></span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
